name: Test audio

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsndfile1 sox
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]
          pip install pyarrow --upgrade
      - name: Test audio with pytest
        run: |
          HF_SCRIPTS_VERSION=master python -m pytest -m audio -sv ./tests/features/test_audio.py
